"""empty message

Revision ID: 6d91da74154f
Revises: 806aa426f6ab
Create Date: 2024-07-25 17:35:12.971913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d91da74154f'
down_revision = '806aa426f6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('purchasePrice')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchasePrice', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
