"""added password fields

Revision ID: 89a5c979077f
Revises: a4d6bb37c1b7
Create Date: 2024-07-24 13:06:18.182910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a5c979077f'
down_revision = 'a4d6bb37c1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio')
    op.drop_table('transaction_history')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('value')
        batch_op.drop_column('cash')
        batch_op.drop_column('revenue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revenue', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('cash', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('value', sa.FLOAT(), nullable=False))

    op.create_table('transaction_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('stock', sa.VARCHAR(length=20), nullable=False),
    sa.Column('shares', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('revenue', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('stock', sa.VARCHAR(length=20), nullable=False),
    sa.Column('shares', sa.INTEGER(), nullable=False),
    sa.Column('purchasePrice', sa.FLOAT(), nullable=False),
    sa.Column('currentPrice', sa.FLOAT(), nullable=False),
    sa.Column('totalValue', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
