"""added password fields

Revision ID: 9a6ac8e67787
Revises: 6c8ac10b0fe9
Create Date: 2024-07-24 14:02:14.598900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6ac8e67787'
down_revision = '6c8ac10b0fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash', sa.Float(), nullable=False, server_default='5000'))
        batch_op.add_column(sa.Column('value', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('revenue', sa.Float(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('revenue')
        batch_op.drop_column('value')
        batch_op.drop_column('cash')

    # ### end Alembic commands ###
