"""updated model descriptions

Revision ID: c8f2391e48ff
Revises: 9a6ac8e67787
Create Date: 2024-07-25 14:41:40.711922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f2391e48ff'
down_revision = '9a6ac8e67787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('purchasePrice', sa.Float(), nullable=False),
    sa.Column('currentPrice', sa.Float(), nullable=False),
    sa.Column('totalValue', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('portfolio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('stock', sa.VARCHAR(length=20), nullable=False),
    sa.Column('shares', sa.INTEGER(), nullable=False),
    sa.Column('purchasePrice', sa.FLOAT(), nullable=False),
    sa.Column('currentPrice', sa.FLOAT(), nullable=False),
    sa.Column('totalValue', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stock')
    # ### end Alembic commands ###
